server:
    port: 8888
    
spring :
    # profile 설정
    config:
        activate :
            on-profile : dev
    # mariadb 설정        
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3306/trackbit
        username: root
        password: 123456789
    #들여쓰기 잘 맞춰야 함
    jpa:
      hibernate: 
        # create, create-drop, update, none create하면 서버재기동할 때마다 새로 테이블 만들어지면서 데이터 날라감, 한 번 만들고 나면 none으로 바꾸기
        ddl-auto:  none
      # 콘솔출력
      show-sql: true     
      properties:
        hibernate:
          # h2
          # dialect: org.hibernate.dialect.H2Dialect
          # mariadb
          dialect: org.hibernate.dialect.MariaDBDialect
          format_sql: true

    # redis
    # docker run -d --name redis-container -p 6379:6379 redis:7.2 //도커에 레디스 실행
    # docker exec -it redis-container redis-cli //리눅스 서버 접근 ping 치면 pong 반환됨
    # docker run -d --name redis-insight -p 8001:5540 redis/redisinsight:latest //redisinsight
    # http://localhost:8001
    # Host : redis 또는 host.docker.internal, port :6379
    # 127.0.0.1:6379> keys *
    # 1) "RT:admin@admin.com"
    # 127.0.0.1:6379> exit
    data:
        redis:
            host: localhost
            port: 6379
            password:
            timeout: 6000ms
    
    ai:
      openai:
        model: ${OPEN_AI_MODEL}
        api:
          key: ${OPEN_AI_KEY}
          url: ${OPEN_AI_URL}

jwt:
  secret: ${JWT_SECRET_KEY}

openApi:
  serviceKey: ${SERVICE_KEY}
  callBackUrl: ${CALLBACKURL}
  dataType: ${TYPE}